image: golang:1.10.3

stages:
  - build
  - test

before_script:
  - mkdir -p ${GOPATH}/src/gitlab.com/xonvanetta/gerish
  - mkdir -p ${CI_PROJECT_DIR}/artifacts
  - go get github.com/tools/godep
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/gitlab.com/xonvanetta/gerish/
  - cd ${GOPATH}/src/gitlab.com/xonvanetta/gerish

build:
  stage: build
  script:
    - godep restore
    - godep go build -o ${CI_PROJECT_DIR}/artifacts/gerish
  artifacts:
    paths:
      - artifacts

test:
  stage: test
  script:
    - godep restore
    - godep go test ./... -v -coverprofile .testCoverage.txt